name: Maxim Haim
favicon: null
layout_spectrum: 0.5338782130274922
typography_spectrum: 1
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#45424b'
    - '#fece9f'
    - '#b3d2fe'
    - '#b65310'
  brandStrength: 0.05404887138865888
  lightness: 0.7864486556500196
  saturation: 0.5964353634044528
  rhythmicContrast: 0.6072064489126205
purpose: []
